### PR TITLE
[#2] Improve yesod scaffold compatibility.

### PR DESCRIPTION
**Pull request by naushadh**
Before submitting your PR, check that you've:

- [X] Bumped the version number
- [X] Documented new APIs with [Haddock markup](https://www.haskell.org/haddock/doc/html/index.html)
- [X] Added [`@since` declarations](http://haskell-haddock.readthedocs.io/en/latest/markup.html#since) to the Haddock

After submitting your PR:

- [X] Update the Changelog.md file with a link to your PR
- [x] Check that CI passes (or if it fails, for reasons unrelated to your change, like CI timeouts)

### CODE REVIEW

**Comment by Burtannia** [comment]
Is this getting merged any time soon? I need this functionality for a project.

**Comment by naushadh** [comment]
@Burtannia merged

**Comment by naushadh** [comment]
@Burtannia CI just passed. released on hackage now: https://hackage.haskell.org/package/persistent-mysql-haskell-0.4.1

Happy hacking!

**Comment by Burtannia** [comment]
@naushadh Thank you!

**Pull request merged**
